version: '3.7'
services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    restart: always
    ports:
      - 3000:3000
    networks:
      - nextjs-network
networks:
  nextjs-network:
    driver: bridge
